trigger:
- master

stages:
  - stage: Install
    jobs:
    - job: Install
      strategy:
        matrix:
          Windows-Python35:
            python.version.major: '3'
            python.version.minor: '5'
            os.image: 'windows-latest'
          Windows-Python36:
            python.version.major: '3'
            python.version.minor: '6'
            os.image: 'windows-latest'
          Windows-Python37:
            python.version.major: '3'
            python.version.minor: '7'
            os.image: 'windows-latest'
          MacOS-Python35:
            python.version.major: '3'
            python.version.minor: '5'
            os.image: 'macOS-latest'
          MacOS-Python36:
            python.version.major: '3'
            python.version.minor: '6'
            os.image: 'macOS-latest'
          MacOS-Python37:
            python.version.major: '3'
            python.version.minor: '7'
            os.image: 'macOS-latest'
          Ubuntu-Python35:
            python.version.major: '3'
            python.version.minor: '5'
            os.image: 'ubuntu-latest'
          Ubuntu-Python36:
            python.version.major: '3'
            python.version.minor: '6'
            os.image: 'ubuntu-latest'
          Ubuntu-Python37:
            python.version.major: '3'
            python.version.minor: '7'
            os.image: 'ubuntu-latest'
        maxParallel: 9

      pool:
        vmImage: $(os.image)

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version.major).$(python.version.minor)'
        displayName: 'Use Python $(python.version.major).$(python.version.minor)'

      - script: python -m pip install --upgrade pip setuptools wheel
        displayName: 'Upgrade pip and setuptools'

      - script: pip install .
        displayName: 'Install putput'
